apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"c67c850d-172a-440b-a7f8-f0dc2cb721e2","creationTimestamp":"2023-12-27T09:46:29Z"}'
  creationTimestamp: "2023-12-27T09:46:29Z"
  name: default-ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 10.244.0.0/16
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
