addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 192.168.1.2
  conditions:
    ready: true
kind: EndpointSlice
metadata:
  creationTimestamp: "2023-12-27T09:42:47Z"
  labels:
    kubernetes.io/service-name: kubernetes
  name: kubernetes
  namespace: default
ports:
- name: https
  port: 6443
  protocol: TCP
