apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syslog-ng
  name: syslog-ng
  namespace: jcnr
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: syslog-ng
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: syslog-ng
      name: syslog-ng
      namespace: jcnr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - command:
        - sh
        - -c
        - HOSTUPTIME=$(cut -d'.' -f1 /proc/uptime) /usr/sbin/syslog-ng -F -f /config/syslog-ng.conf
          --persist-file /config/syslog-ng.persist --pidfile=/config/syslog-ng.pid
          --control=/config/syslog-ng.ctl --stderr --no-caps
        env:
        - name: CONTRAIL_VROUTER_LOG_PATH
          value: /var/log/jcnr/
        image: svl-artifactory.juniper.net/contrail-docker/x86_64/syslog-ng:v6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - syslog-ng-ctl
            - stats
            - --control=config/syslog-ng.ctl
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: syslog-ng
        ports:
        - containerPort: 6601
          name: syslog-tcp
          protocol: TCP
        - containerPort: 5514
          name: syslog-udp
          protocol: UDP
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        startupProbe:
          exec:
            command:
            - syslog-ng-ctl
            - stats
            - --control=config/syslog-ng.ctl
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/syslog-ng.conf
          name: config
          subPath: syslog-ng.conf
        - mountPath: /var/log/jcnr/
          name: contraillogs
        - mountPath: /var/log/jcnr_notifications.json
          name: jcnrnotifications
        - mountPath: /etc/localtime
          name: host-time
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
      serviceAccount: crpd
      serviceAccountName: crpd
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: syslog-config
        name: config
      - hostPath:
          path: /var/log/jcnr/
          type: ""
        name: contraillogs
      - hostPath:
          path: /var/log/jcnr/jcnr_notifications.json
          type: FileOrCreate
        name: jcnrnotifications
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
