apiVersion: events.k8s.io/v1
deprecatedCount: 7208
deprecatedFirstTimestamp: "2023-12-27T09:47:05Z"
deprecatedLastTimestamp: "2024-01-02T16:42:17Z"
deprecatedSource:
  component: kubelet
  host: sharmag-k8s-master-pnad30.englab.juniper.net
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-12-27T09:47:05Z"
  name: kube-multus-ds-bxz6m.17a4a739beb2cfb7
  namespace: kube-system
note: 'Nameserver limits were exceeded, some nameservers have been omitted, the applied
  nameserver line is: 10.84.5.101 172.21.200.60 66.129.233.81'
reason: DNSConfigForming
regarding:
  apiVersion: v1
  kind: Pod
  name: kube-multus-ds-bxz6m
  namespace: kube-system
  resourceVersion: "1075"
  uid: f0b550d8-53ff-487c-ab12-30d018e7020c
reportingController: kubelet
reportingInstance: sharmag-k8s-master-pnad30.englab.juniper.net
type: Warning
