apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-12-27T09:42:50Z"
  name: kube-controller-manager
  namespace: kube-system
spec:
  acquireTime: "2023-12-27T09:42:50.115117Z"
  holderIdentity: sharmag-k8s-master-pnad30.englab.juniper.net_8eadf6dc-3d1c-4bb3-842e-0c8256545064
  leaseDurationSeconds: 15
  leaseTransitions: 0
  renewTime: "2024-01-02T16:45:36.654828Z"
